[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
fs_permissions = [{ access = "read", path = "./src/build-artifacts" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
